name: Trigger auto deployment for container-app-guhfhhijabdbu

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '//**'
    - '.github/workflows/container-app-guhfhhijabdbu-AutoDeployTrigger-d31551e0-d581-46a3-816e-a4b659e0cdc8.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPGUHFHHIJABDBU_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPGUHFHHIJABDBU_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPGUHFHHIJABDBU_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPPGUHFHHIJABDBU_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPGUHFHHIJABDBU_REGISTRY_PASSWORD }}
          containerAppName: container-app-guhfhhijabdbu
          resourceGroup: expresssamplea5b6bcaa
          imageToBuild: default/container-app-guhfhhijabdbu:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


